# Generated by Django 4.2 on 2024-04-18 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_users',
        ),
        migrations.AddField(
            model_name='product',
            name='jjim_users',
            field=models.ManyToManyField(related_name='jjim_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
